//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace karasustilyuzmecom
{
    public partial class SiteMaster
    {
        /// <summary>
        /// CanonicalPlaceHolder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder CanonicalPlaceHolder;

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// litMasterFormMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMasterFormMessage;

        /// <summary>
        /// txtMasterName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMasterName;

        /// <summary>
        /// ddlMasterCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMasterCourse;

        /// <summary>
        /// txtMasterPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMasterPhone;

        /// <summary>
        /// txtMasterEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMasterEmail;

        /// <summary>
        /// btnMasterSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnMasterSubmit;

        /// <summary>
        /// txtNewsletterEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewsletterEmail;

        /// <summary>
        /// btnNewsletterSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNewsletterSubmit;
    }
}